apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  selector:
    app: guestbook-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.3.243.227
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127
